### ISSUE TITLE
(Discord) Delete thread on exit

### ISSUE THREAD

**Issue by R0flcopt3r** [binwiederhier/replbot#23]
It creates a fair bit of noise when it doesn't delete the threads when the session is over.

An option in `config.yaml` to enable/disable deletion would be a nice companion.

**Comment by binwiederhier** [comment]
I think I could just make that the default behavior. I have thought the same thing. I'll do that. Thanks for creating an issue.

**Comment by binwiederhier** [comment]
Oh wait did you mean archive or delete?

**Comment by R0flcopt3r** [comment]
I don't think Discord has an archive feature?

Deletion is what I'd suggest anyways. Personally, I don't see any reason keep it around.

**Comment by binwiederhier** [comment]
Since it was so easy I just tagged v0.1.6 with new packages that archives the thread after a session is closed. I honestly think deleting is a bit extreme anyway. If you feed strongly about it I may reconsider, but I like archiving better.

**Comment by MindTooth** [comment]
Nice!  

Could I build upon this and maybe suggest that the REPL output message also is removed?  AFAIK, it's left behind.

**Comment by binwiederhier** [comment]
So since this is the second time it came up I think I should probably do it: https://github.com/binwiederhier/replbot/issues/4

A coworker had asked to make a "hide the evidence" command. But I think it goes in the same direction. I'll think of something.

**Comment by R0flcopt3r** [comment]
> Since it was so easy I just tagged v0.1.6 with new packages that archives the thread after a session is closed. I honestly think deleting is a bit extreme anyway. If you feed strongly about it I may reconsider, but I like archiving better.

Awesome! \o/ I do not feel strongly about it either way.

**Comment by R0flcopt3r** [comment]
I just gave it a spin, and archiving is perfect! I wasn't sure how it actually worked in discord until now.

I suppose we can close this issue then?

**Comment by binwiederhier** [comment]
Sweet. Glad you like it.
