### ISSUE TITLE
Web terminal not working

### ISSUE THREAD

**Issue by mamercad** [binwiederhier/replbot#41]
```bash
❯ sudo grep ^web-add /etc/replbot/config.yml
web-address: [redacted]:[redacted]

❯ ttyd -h 2>&1 | head -1
ttyd is a tool for sharing terminal over the web

❯ which ttyd
/usr/local/bin/ttyd
```

![image](https://user-images.githubusercontent.com/6192266/135535857-c03df8f0-61ca-437e-87ee-5dca979e2c6f.png)

Also, it looks like it's completely missing from the Slack message `http:///uQURnJBV2C`.

**Comment by binwiederhier** [comment]
Oh that shouldn't happen. I'll look tonight.

**Comment by binwiederhier** [comment]
I can reproduce the issue. The web option should not be available when `web-host` is not defined, so it shouldn't show up in the help message, and certainly not do what is shown in the screenshot.

**Comment by binwiederhier** [comment]
I released https://github.com/binwiederhier/replbot/releases/tag/v0.6.2 with a fix for this. The main problem though was the documentation issue you fixed in the config.yml. Thank you!
