### ISSUE TITLE
REPLbot no longer works on Discord

### ISSUE THREAD

**Issue by runbgp** [binwiederhier/replbot#45]
Tried to spin up REPLbot for another Discord server today and can't seem to get it to work. I've tried with both normal permissions + administrator permissions on the bot as well as the role in the server. In servers, it doesn't seem to send any messages at all when mentioned. It does reply in DMs, but is unable to recognize any commands. Screenshot attached.
![Screenshot 2022-08-29 004706](https://user-images.githubusercontent.com/99215336/187125136-4869ffce-378e-48c8-8304-1ecd8814b49b.png)

**Comment by binwiederhier** [comment]
If you are DMing with the bot, you don't need to say its name. 
Other than that, I'm not really working on the bot anymore, so you'll have to figure out problems yourself.
