### ISSUE TITLE
Add option to allow repl in main channel with command in thread on the message

### ISSUE THREAD

**Issue by CraftSpider** [binwiederhier/replbot#7]
One issue I can think of is Slack not allowing edits after a certain point, so this may not end up being practical

**Comment by binwiederhier** [comment]
Typing `@replbot php split` does that, does it not? It merely defaults to `thread` when you're starting it from a thread.

**Comment by CraftSpider** [comment]
Yep, it seems like it already works fine, sorry for the spurious issue.
